### ISSUE TITLE
Undetected hooking?

### ISSUE THREAD

**Issue by Jeimy041** [sstokic-tgm/Gladiatorcheatz-v2.1#10]
If so can you explain how to realize if is the detected VMT or not by myself?
Thank you!!

**Comment by sstokic-tgm** [comment]
The vmt hooking class uses the shadow table technique which is lesser detectable than the original vmt hooking. But the state of art as it is no matter what vmt hooking is used, it is still detected.

But you get then busted when that module is streamed by VAC on your computer.
