### ISSUE TITLE
For Which Game*

### ISSUE THREAD

**Issue by hasanalizxc** [sstokic-tgm/Gladiatorcheatz-v2.1#2]
Hi sstokic,

Hope you are well. Is this cheat for which game?

**Comment by sstokic-tgm** [comment]
csgo, but since panorama update, you have to update it yourself or take a look at one of the forks, e.g: https://github.com/nnk97/Gladiatorcheatz-v2.1

**Comment by hasanalizxc** [comment]
Uhh i got it. Could you please make one for CS 1.6? :/ My pc is really really old and only can play CS 1.6 online with maximum 10 players. Because when i join more than 10 players server lag, ms and ping increases maximum degree. And i can play Zuma (maybe you know) offline.

Thanks.
