### ISSUE TITLE
Crash after joining 2nd game

### ISSUE THREAD

**Issue by unniggable** [sstokic-tgm/Gladiatorcheatz-v2.1#6]
I can play the first game fine but when i go into the second game my game just closes. I'm compiling in Release x86 and when i debug it says "tier0.dll!0f1dabcd()" "Frames below may be incorrect and/or missing, no symbols loaded for tier0.dll"

**Comment by sstokic-tgm** [comment]
That issue shouldn't be present anymore. You can aswell comment out the UpdateLbyBreaker function since fakes are patched.
